CREATE TABLE HOSPITAL_DETAILS<H_NAME VARCHAR<100>,H_R NAME VARCHAR<20>,ADDRESS ADDR,CONTACT NO NUMBER<10> PRIMARY KEY,EMAIL VARCHAR<30>,FOREIGN KEY<H_NAME,H_R NAME>,REFERENCES<HOSPITAL_VALIDATION<H_NAME,H_R NAME>>;
CREATE TABLE HOSPITAL_DETAILS<H_NAME VARCHAR<100>,HR_NO VARCHAR<20>,ADDRESS ADDR,CONTACT_NO NUMBER<10>PRIMARY KEY,EMAIL VARCHAR<30>,FOREIGN KEY<H_NAME,HR_NAME>REFERENCES HOSPITAL_VALIDATION<H_NAME,HR_NAME>>;
CREATE TABLE HOSPITAL_VALIDATION<H_NAME VARCHAR<100>,HR_NO VARCHAR<20>,PRIMARY KEY<H_NAME,HR_NO>>;
